name:                ants
version:             0.1.0.0
github:              "jlavelle/ants"
license:             BSD3
author:              "John C. Lavelle"
maintainer:          "john@lavelle.tech"
copyright:           "2018 John C. Lavelle"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jlavelle/ants#readme>

dependencies:
- base >= 4.7 && < 5
- gloss
- containers
- dhall
- text
- bytestring

library:
  source-dirs: src

executables:
  ants-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ants

tests:
  ants-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ants
